baseurl:
title: The Society for Early Scottish Culture
subtitle:
author: The Society for Early Scottish Culture
description:
name:
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/Chicago
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
